repos:
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean
  - id: nbdev_export
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.18
  hooks:
  - id: circleci-config-validate